/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JFrame;

/**
 *
 * @author ariel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itCadastrarDespesa = new javax.swing.JMenuItem();
        itListarDespesa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btCadRecebivel = new javax.swing.JMenuItem();
        btListRecebivel = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        itCadastrarCategoria = new javax.swing.JMenuItem();
        itListarCategorias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 0, 102));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Despesa");

        itCadastrarDespesa.setText("Cadastrar Despesa");
        itCadastrarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itCadastrarDespesaActionPerformed(evt);
            }
        });
        jMenu1.add(itCadastrarDespesa);

        itListarDespesa.setText("Listar Dispesas");
        itListarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itListarDespesaActionPerformed(evt);
            }
        });
        jMenu1.add(itListarDespesa);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Recebivel");

        btCadRecebivel.setText("Cadastrar Recebivel");
        btCadRecebivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadRecebivelActionPerformed(evt);
            }
        });
        jMenu2.add(btCadRecebivel);

        btListRecebivel.setText("Listar Recebivel");
        btListRecebivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListRecebivelActionPerformed(evt);
            }
        });
        jMenu2.add(btListRecebivel);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Relatorios");
        jMenuBar1.add(jMenu3);

        jMenu11.setForeground(new java.awt.Color(255, 255, 255));
        jMenu11.setText("Categorias");

        itCadastrarCategoria.setText("Cadastrar Categoria");
        itCadastrarCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itCadastrarCategoriaMouseClicked(evt);
            }
        });
        itCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itCadastrarCategoriaActionPerformed(evt);
            }
        });
        jMenu11.add(itCadastrarCategoria);

        itListarCategorias.setText("Listar Categirias");
        itListarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itListarCategoriasActionPerformed(evt);
            }
        });
        jMenu11.add(itListarCategorias);

        jMenuBar1.add(jMenu11);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Usuario");

        jMenuItem1.setText("Cadastrar Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setText("Sobre");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itCadastrarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itCadastrarDespesaActionPerformed
        JFrame cadDespesa = new CadastroDespesa();
        cadDespesa.setVisible(true);
    }//GEN-LAST:event_itCadastrarDespesaActionPerformed

    private void itCadastrarCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itCadastrarCategoriaMouseClicked

    }//GEN-LAST:event_itCadastrarCategoriaMouseClicked

    private void itCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itCadastrarCategoriaActionPerformed
        JFrame cadCategoria = new TelaCadastroCategoria();
        cadCategoria.setVisible(true);
    }//GEN-LAST:event_itCadastrarCategoriaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFrame cadUsuario = new TelaCadastroUsuario();
        cadUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itListarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itListarCategoriasActionPerformed
        JFrame listCategorias = new TelaListaCategoria();
        listCategorias.setVisible(true);
    }//GEN-LAST:event_itListarCategoriasActionPerformed

    private void itListarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itListarDespesaActionPerformed
        JFrame listDespesa = new TelaListarDespesa();
        listDespesa.setVisible(true);
    }//GEN-LAST:event_itListarDespesaActionPerformed

    private void btCadRecebivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadRecebivelActionPerformed
        JFrame cadastroRecebivel = new CadastroRecebivel();
        cadastroRecebivel.setVisible(true);
    }//GEN-LAST:event_btCadRecebivelActionPerformed

    private void btListRecebivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListRecebivelActionPerformed
        JFrame listRecebivel = new TelaListarRecebivel();
        listRecebivel.setVisible(true);
    }//GEN-LAST:event_btListRecebivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btCadRecebivel;
    private javax.swing.JMenuItem btListRecebivel;
    private javax.swing.JMenuItem itCadastrarCategoria;
    private javax.swing.JMenuItem itCadastrarDespesa;
    private javax.swing.JMenuItem itListarCategorias;
    private javax.swing.JMenuItem itListarDespesa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
